language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t monroe0219/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true BAM89/docker-react npm run test
