FROM node:alpine
RUN mkdir -p /app
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
FROM nginx
EXPOSE 80
#COPY --from=0 /app/build /usr/share/nginx/html
COPY . /usr/share/nginx/html